// Generated by https://quicktype.io

export interface IError {
  headers:    Headers;
  status:     number;
  statusText: string;
  url:        string;
  ok:         boolean;
  name:       string;
  message:    string;
  error:      Error;
}

export interface Error {
  error: string;
}

export interface Headers {
  normalizedNames: NormalizedNames;
  lazyUpdate:      null;
}

export interface NormalizedNames {
}
